# Generated by Django 5.0.6 on 2024-05-14 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.member')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Done', 'Done')], default='To Do', max_length=100)),
                ('priority', models.CharField(choices=[('Normal Priority', 'Normal'), ('MID Priority', 'Mid'), ('Immediate Priority', 'Immediate')], default='Normal Priority', max_length=100)),
                ('which_Type', models.CharField(choices=[('Feature', 'Feature'), ('Bug Fix', 'Bug Fix'), ('Code Test', 'Code Test'), ('Task', 'Task')], default='Task', max_length=100)),
                ('task_Value', models.DecimalField(decimal_places=0, max_digits=5)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.member')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField()),
                ('commernter', models.ManyToManyField(to='workspaces.member')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('start_Date', models.DateTimeField()),
                ('end_Date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Testing', 'Testing'), ('Done', 'Done')], default='To Do', max_length=100)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.member')),
            ],
        ),
    ]
