# Generated by Django 5.0.6 on 2024-05-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_member_role_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='commernter',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='commernter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.member'),
        ),
    ]
