# Generated by Django 5.0.6 on 2024-05-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_remove_taskcomment_commernter_taskcomment_commernter'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrum',
            name='timeline_Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.timeline'),
        ),
        migrations.AddField(
            model_name='task',
            name='scrum_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.scrum'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.task'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='workspace_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
