# Generated by Django 5.0.6 on 2024-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_scrum_timeline_name_task_scrum_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
