# Generated by Django 5.0.6 on 2024-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_timeline_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
