# Generated by Django 5.0.6 on 2024-05-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_timeline_comment_alter_timeline_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='workspace_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
