# Generated by Django 5.0.6 on 2024-05-17 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_alter_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Associate Manager', 'Associate Manager'), ('Team Leader', 'Team Leader'), ('Member', 'Member')], default='Member', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('workspace_Name', 'user')},
        ),
    ]
