# Generated by Django 5.0.6 on 2024-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Associate Manager', 'Associate Manager'), ('Team Leader', 'Team Leader'), ('Member', 'Member')], default='Member', max_length=100),
        ),
    ]
