# Generated by Django 5.0.6 on 2024-05-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_alter_member_role'),
        ('workspaces', '0010_member_pending'),
    ]

    operations = [
    ]
