# Generated by Django 5.0.6 on 2024-05-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_timeline_remaining_time_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.member'),
        ),
    ]
