# Generated by Django 5.0.6 on 2024-05-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_alter_scrum_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], default='LOW', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Done', 'Done')], default='To Do', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_Value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='which_Type',
            field=models.CharField(blank=True, choices=[('Feature', 'Feature'), ('Bug Fix', 'Bug Fix'), ('Code Test', 'Code Test'), ('Task', 'Task')], default='Task', max_length=100, null=True),
        ),
    ]
