# Generated by Django 5.0.6 on 2024-05-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_alter_task_assign_alter_task_priority_and_more'),
        ('workspaces', '0014_alter_workspace_created_at_and_more'),
    ]

    operations = [
    ]
