# Generated by Django 5.0.6 on 2024-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_alter_timeline_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
