# Generated by Django 5.0.6 on 2024-05-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_alter_timeline_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='commernter',
            new_name='commenter',
        ),
    ]
