# Generated by Django 5.0.6 on 2024-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0020_rename_commernter_taskcomment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
